apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multiarch-tuning-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multiarch-tuning-operator-bundle
    app.kubernetes.io/part-of: multiarch-tuning-operator
  name: multiarch-tuning-operatorslns
spec:
  port:
    targetPort: 5001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: multiarch-tuning-operator-bundle
    weight: 100
status: {}
