apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multiarch-tuning-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multiarch-tuning-operator-bundle
    app.kubernetes.io/part-of: multiarch-tuning-operator
  name: multiarch-tuning-operator-bundle
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multiarch-tuning-operator-bundle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multiarch-tuning-operator-bundle
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle@sha256:e4d04915efcaff649a4492822f4dc13a5c8883bdaa4cffac2705142257993b7e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
status: {}
